#!/usr/bin/env bash

usage="Usage: $(basename "$0") (deploy | diff | serve)

Commands:
  deploy     Upload to Github
  diff       Show changes"

TARGET_REPO="etaletai13/gmc-bin"
RELEASES_BRANCH="release"
PY_CMD="python3"

rootPath="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
commitHash=$(git rev-parse HEAD)
commitMessage=$(git log -1 --pretty=%B)
GITHUB_REPO=https://${GH_TOKEN:-git}@github.com/${TARGET_REPO}.git
rm -rf go-musicoin
git add -A
git commit -m "$commitMessage" -m "Generated by $commitHash."
git tag -d $(git tag)
git tag "v1.0.0"
git push origin --tags -f

