#!/usr/bin/env bash

usage="Usage: $(basename "$0") (deploy | diff | serve)

Commands:
  deploy     Upload to Github
  diff       Show changes"

TARGET_REPO="etaletai13/gmc-bin"
RELEASES_BRANCH="release"
PY_CMD="python3"

rootPath="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  
# Pull hash and commit message of the most recent commit
commitHash=$(git rev-parse HEAD)
commitMessage=$(git log -1 --pretty=%B)

# Clone the GitHub Pages branch and rsync it with the newly generated files
GITHUB_REPO=https://${GH_TOKEN:-git}@github.com/${TARGET_REPO}.git

git add -A
git status -s

git commit -m "$commitMessage" -m "Generated by $commitHash."
git push origin $RELEASES_BRANCH

