language: node_js
os: linux
dist: trusty
node_js: 
  - "8.0.0"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
after_success:
  - cd "$TRAVIS_BUILD_DIR"
  - git add .
  - git -c user.name='travis' -c user.email='travis' commit -am "release"
  - git tag "v0.1.0"
  - git push -f -q https://etaletai13:$GH_TOKEN@github.com/etaletai13/gmc --tags
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  on:
    repo: etaletai13/gmc-bin
    branch: staging
    tags: true
