os: linux
language: node_js
node_js: 8.9.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: npm
  email: parker.casey@gmail.com
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
    tags: true
    repo: etaletai13/gmc-bin
    branch: npm
