language: node_js
node_js: 
  - "8.0.0"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - git config --local user.name "etaletai13"
  - git config --local user.email "parker.casey@gmail.com"
  - git remote add upstream https://etaletai13:$GH_TOKEN@github.com/etaletai13/gmc
  - git fetch --unshallow upstream
after_success:
  - git add bin/*
  - git branch -d latest
  - git commit -am "build $TRAVIS_BUILD_NUMBER"
  - git push upstream --all -fq
before_deploy:
  - git tag -d $(git tag)
  - git tag "release-$(date +'%Y%m%d%H')"
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: ./**/*
  skip_cleanup: true
  options:
    name: "gmc-bin"
    body: "Prebuilt binaries for go-musicoin"
    draft: true
  on:
    repo: etaletai13/gmc-bin
    branch: 
      - latest
