language: node_js
node_js:
- 8.0.0
services:
- docker
before_script:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
script:
- yarn before-install
before_deploy:
- rm -rf go-musicoin
- git add -A
- sh .push.sh deploy
deploy:
  provider: npm
  email: parker.casey@gmail.com
  api_key:
    secure: onBY+uMj7DF5xlsRFJ0v0cRjUWu/zz4oqLxIdhSIAI2xR+m0iGwnCQtoLhpzbBgt9/IE0dKGcXgle8rAoTBheHI7bUkbdao1eDHGd5tS3Gc9WCf8J49/34YOftP3RW24CYtCoT/sl62JPNNI5GXsvaZNp0raQUgsjL+hq7lVzdrl8Y/c5VlTWRkzkQEeidJFwYiMkdiwnWyBUoMrH9PwsCpOmQnWfnm3HhYGktuS9X43Z9PCMjt5p6y7Y8tLiwT6AmOC6MqKKy+SuWb5bArMchuiRqfLmMAAWUNhaqKze8Vm5+aKaRjuRU+wwh7DfKrrl8gxHec4j4TClewm2U8Abw6JGn8gkOiSVDOCVWKeR9Oz/LXQNM0peO+PJdsGUexMCzK5hWsOIoDUig9vOkybQHByQthvVhqtbBaX7dmbUXFUVlStL6IvR+x43n7lHewzYUxMk1oXelzSAeN4Bjfsb/VCuZ/SJBJKHlHPM/p0yV2T5QIsNnlMLV30OyeongU2zt0XGdHMORSletaQLUfwTHdKDJpfiiVkDv3NHUj4MSGHWZNFzNOtzj9L56IklFPmhgBor7EEgwghrpY7kjn8dYfj+hJTn88jovP6HUlFm9FVD6EjYjOb7VGGky6kjJgtRf7NT7x74s9Y7LkmjtNbrQwZt/wpvQJrZK6LyUSlZM4=
  on:
    tags: true
    repo: etaletai13/gmc-bin
