language: node_js
node_js: 
  - "8.0.0"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
after_success:
  - git config --local user.name "etaletai13"
  - git config --local user.email "parker.casey@gmail.com"
  - git remote add upstream https://etaletai13:$GH_TOKEN@github.com/etaletai13/gmc
  - git fetch --unshallow upstream
  - git add bin/*
  - git commit -am "build $TRAVIS_BUILD_NUMBER"
before_deploy:
  - git tag "$(date +'%Y%m%d%H')-$(git log --format=%h -1)"
  - git push upstream "release-$TRAVIS_BUILD_NUMBER" --tags
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "**/*"
  skip_cleanup: true
  on:
    repo: etaletai13/gmc-bin
    branch: 
      - staging
      - master
    tags: false
