language: node_js
os: linux
dist: trusty
node_js: 
  - "8.0.0"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
after_success:
  - git add .
  - git commit -am "build $TRAVIS_BUILD_NUMBER"
  - git remote add pushback https://etaletai13:$GH_TOKEN@github.com/etaletai13/gmc
  - git checkout -b latest
  - git fetch --unshallow pushback
  - git push pushback latest -fq
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  on:
    repo: etaletai13/gmc-bin
    branch: staging
