os: linux
dist: trusty
services: docker
language: node_js
node_js: stable
deploy:
  provider: npm
  email: parker.casey@gmail.com
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  file_globs: true
  files: '*'
  on:
    repo: etaletai13/gmc-bin
    branch: dev6
