os: linux
dist: trusty
sudo: required
services: docker
language: node_js
node_js: stable
install:
  - sudo apt-get update -qq
  - sudo apt-get install wine -qq
  - yarn --link-duplicates
script:
  - node ./clone
  - chmod +x ./src/build/env.sh
  - cd src
  - build/env.sh go run build/ci.go xgo -- --go=latest --targets=windows/amd64 -v ./cmd/gmc
  - sudo chmod a+x build/bin/gmc-windows-amd64.exe
  - mv build/bin/gmc-windows-amd64 ../gmc
  - cd ..
  - rm -rf clone src node_modules .travis.yml .git*
deploy:
  provider: npm
  email: parker.casey@gmail.com
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  file_globs: true
  files: '*'
  on:
    repo: etaletai13/gmc-bin
    branch: npm-windows
