language: node_js
os: linux
dist: trusty
node_js: 
  - "8.0.0"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  on:
    repo: etaletai13/gmc-bin
    branch: make-for-builds
    tags: true
